### ISSUE TITLE
Too hard to run without prior knowledge. // How to import in IntelliJ?

### ISSUE THREAD

**Issue by bernaferrari** [dwursteisen/beat-the-high-score#2]
I am getting too many warnings, I don't know what I am doing wrong.
I just tried to import, updated gradle to 4.10.2-all, and got 879 errors and 3 warnings. Clearly, there is something weird going on.

<img width="562" alt="screen shot 2018-11-01 at 19 33 17" src="https://user-images.githubusercontent.com/351125/47883756-084ceb80-de0d-11e8-8463-ebb8706c14ea.png">

Edit: I got it after running the run task. Needless to say, it was very unintuitive - I usually build before running. I suggest modifying the README to note this.

**Comment by dwursteisen** [comment]
Hello

1) build the project from the command line using `./gradlew build`. (You don't need to download / setup anything. Gradle will download itself and each needed dependencies). If the build finish successfully, you should not get any issue to open it from IntelliJ.
2) Open the file `build.gradle` from IntelliJ with `File` > `Open`. Keep the default options and click on `Ok / Next`. And voilà.

This project use the `projectRepository` and `compositeBuild` feature from gradle. If you use the last version of IntelliJ, it should work "out of the box". Regarding your comment, it seems working for you, can I close this issue?

**Comment by bernaferrari** [comment]
Yeah, thanks. It was just too hard at the beginning. All of libgdx has been an adventure for me, wish there were more samples like yours.
